export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const ADD_INNER_ITEM: "ADD_INNER_ITEM" = "ADD_INNER_ITEM";
export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const REMOVE_INNER_ITEM: "REMOVE_INNER_ITEM" = "REMOVE_INNER_ITEM";
export const UPDATE_CONSTRUCTOR_LIST: "UPDATE_CONSTRUCTOR_LIST" = "UPDATE_CONSTRUCTOR_LIST";
export const RESET_CONSTRUSTOR: "RESET_CONSTRUSTOR" = "RESET_CONSTRUSTOR";